name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pylint || true

      - name: Run unit tests
        run: python -m unittest discover

      - name: Lint with pylint
        run: pylint simple_math.py test_simple_math.py || true

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint simple_math.py test_simple_math.py

      - name: Build Docker image
        run: docker build -t simplemath-app .

